openapi: 3.0.2
x-stoplight:
  id: a7ime4fyhchil
info:
  version: "1.0"
  title: Welcome to Fergus Jobs API!
  description: This API allows users to view a users job list
  contact:
    name: Ben Berry
    url: benrhysberry.dev
    email: ben.berry@developersinstitute.co.nz
  license:
    name: example license
    url: exampleurl.com
servers:
  - url: "http://localhost:5001/api"
    description: Development server
paths:
  /jobs:
    get:
      summary: Returns the job list
      description: Get all jobs
      operationId: get-jobs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    jobs:
                      - jobId: 1
                        status: completed
                        dateCreated: "2022-06-14T23:59:21.000Z"
                        customer: Dwight Schrute
                        notes:
                          - Job complete 2nd June 22
                          - New note
                          - New note
                          - New note
                          - Updated Note 8
                          - vrvrv
                      - jobId: 2
                        status: completed
                        dateCreated: "2022-06-24T23:59:21.000Z"
                        customer: Jim Halpert
                        notes:
                          - Completed job 01/07/22
                          - Updated Note 8
                      - jobId: 3
                        status: invoicing
                        dateCreated: "2022-07-12T23:59:21.000Z"
                        customer: Michael Scott
                        notes:
                          - Called customer and set job for 20th July
                          - Customer called and rescheduled to 1st August
                          - Job completed 20th August
                      - jobId: 4
                        status: active
                        dateCreated: "2022-07-19T23:59:21.000Z"
                        customer: Dwight Schrute
                        notes:
                          - Call customer to organise a time to meet and price
                          - Job schedule for 1st September
                      - jobId: 5
                        status: to price
                        dateCreated: "2022-08-20T23:59:21.000Z"
                        customer: Stanley
                        notes:
                          - Call customer to organise a time to meet and price
                          - Updated Note 8
                    currentPage: 1
                    totalPages: 2
                    itemsPerPage: 5
                    totalItems: 6
                properties:
                  jobs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Job"
                  currentPage:
                    type: integer
                  totalPages:
                    type: integer
                  itemsPerPage:
                    type: integer
                  totalItems:
                    type: integer
                required:
                  - jobs
                  - currentPage
                  - totalPages
                  - itemsPerPage
                  - totalItems
              examples:
                example-1:
                  value:
                    jobs:
                      - jobId: 1
                        status: completed
                        dateCreated: "2022-06-14T23:59:21.000Z"
                        customer: Dwight Schrute
                        notes:
                          - Job complete 2nd June 22
                      - jobId: 2
                        status: completed
                        dateCreated: "2022-06-24T23:59:21.000Z"
                        customer: Jim Halpert
                        notes:
                          - Completed job 01/07/22
                    currentPage: 1
                    totalPages: 3
                    itemsPerPage: 2
                    totalItems: 6
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Internal Server Error
      parameters:
        - schema:
            type: integer
            minLength: 1
            minimum: 1
            default: 1
          in: query
          name: page
          description: Determines page of results
        - schema:
            type: integer
            minimum: 1
            maximum: 100
          in: query
          name: limit
          description: Determines how many results per page
        - schema:
            type: string
            enum:
              - status
              - customerName
              - date
              - jobId
          in: query
          name: sortBy
          description: Sorts the jobs depending on query passed
        - schema:
            type: string
            enum:
              - scheduled
              - active
              - invoicing
              - to price
              - completed
          in: query
          name: orderBy
          description: Determines order of sortBy query
        - schema:
            type: string
          in: query
          name: status
          description: Filter by status
    parameters: []
  "/jobs/:id":
    get:
      summary: Your GET endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  job:
                    $ref: "#/components/schemas/JobById"
              examples:
                example-1:
                  value:
                    jobId: 1
                    status: scheduled
                    dateCreated: "2019-08-24T14:15:22Z"
                    notes:
                      - string
                    customer:
                      name: John Smith
                      email: john.smith@gmail.com
                      phone: "0224561789"
                      address:
                        street: 1 Fake Street
                        suburb: Taradale
                        city: Napier
                        region: Hawkes Bay
                        country: New Zealand
                        postcode: 4112
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Please enter a valid id
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Id does not exist
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Internal Server Error
      operationId: get-jobs-id
      description: Gets a single job by id
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: query
          name: id
          description: A specific job id
    parameters: []
    put:
      summary: ""
      operationId: "put-jobs-:id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"
              examples:
                example-1:
                  value:
                    jobId: 0
                    status: scheduled
                    dateCreated: "2019-08-24T14:15:22Z"
                    notes:
                      - string
                    customer: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Please ensure you have filled in the required field
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Id does not exist
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                example-1:
                  value:
                    message: Internal Server Error
      description: Allows the user to add notes to the specific job
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: query
          name: id
          description: A specific job id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
              required:
                - notes
            examples:
              example-1:
                value:
                  notes: Example note
        description: Add note to a specific job
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
      x-examples:
        example-1:
          message: Internal Server Error
      title: Error
      description: Model of error responses
    Job:
      title: Job
      x-stoplight:
        id: dqzb912lnm5e2
      type: object
      description: Job & Customer information
      x-examples:
        example-1:
          jobId: 1
          status: scheduled
          dateCreated: "2022-06-14 23:59:21"
          customer: John Smith
          notes:
            - Job created
      properties:
        jobId:
          type: integer
        status:
          type: string
          enum:
            - scheduled
            - active
            - invoicing
            - to price
            - completed
        dateCreated:
          type: string
          format: date-time
        notes:
          type: array
          nullable: true
          items:
            type: string
        customer:
          type: string
      required:
        - jobId
        - status
        - dateCreated
        - customer
    Customer:
      x-examples:
        example-1:
          customer:
            name: John Smith
            email: john.smith@gmail.com
            phone: "0224561789"
            address:
              street: 1 Fake Street
              suburb: Taradale
              city: Napier
              region: Hawkes Bay
              country: New Zealand
              postcode: 4112
      title: Customer
      description: Model of customer data
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: object
          required:
            - street
            - city
            - region
            - country
            - postcode
          properties:
            street:
              type: string
            suburb:
              type: string
            city:
              type: string
            region:
              type: string
            country:
              type: string
            postcode:
              type: integer
              maximum: 9999
      required:
        - name
        - email
        - phone
        - address
    JobById:
      x-examples:
        example-1:
          job:
            jobId: 1
            status: completed
            dateCreated: "2022-06-14T23:59:21+00:00"
            notes:
              - Job complete 2nd June 22
            customer:
              name: Dwight Schrute
              email: dwight.schrute@beetfarms.com
              phone: "0213456782"
              address:
                street: 1 King Street
                suburb: Taradale
                city: Napier
                region: Hawkes Bay
                country: New Zealand
                postcode: 4112
      type: object
      title: JobById
      description: Specific job by id response
      properties:
        jobId:
          type: integer
        status:
          type: string
        dateCreated:
          type: string
        notes:
          type: array
          items:
            type: string
        customer:
          $ref: "#/components/schemas/Customer"
